# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: appium-android
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
       api-level:  [25]
       target:  [default]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'
    - uses: actions/setup-node@v3
      with:
        node-version: '12'
    - name: Install JAXB dependency
      run: |
        echo "<dependency>" >> pom.xml
        echo "    <groupId>javax.xml.bind</groupId>" >> pom.xml
        echo "    <artifactId>jaxb-api</artifactId>" >> pom.xml
        echo "    <version>2.3.1</version>" >> pom.xml
        echo "</dependency>" >> pom.xml    
    - run: |
            npm install -g appium@v1.20.2
            appium -v
            appium &>/dev/null &
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v1
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: mvn test -D"cucumber.filter.tags=@smoke"
