name: appium-android
on:
  push:
    branches: [ "ci_actions" ]
  pull_request:
    branches:
      - main
      - ci_actions
jobs:
  run-mobile-tests:
    runs-on: macos-latest

    steps:
    - name: pull the project to the runner
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '12'
        
    - name: Install Appium
      run: |
        npm install -g appium@1.22
        appium -v
        appium &>/dev/null &

    - name: Run Appium Android Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 24
        script: mvn test -D"cucumber.filter.tags=@smoke"

